let map, stations=[], filteredStations=[], markers=new Map(), markerLayer, routeLayer, routeLine=null, routeMode=false, routeStations=[];
const riverColors={"한강":"#2563eb","금강":"#111827","영산강":"#dc2626","낙동강":"#16a34a","기타":"#64748b"};
const state={search:"",rivers:new Set(),groups:new Set()};
document.addEventListener("DOMContentLoaded",init);
async function init(){initMap();const res=await fetch("./data/stations.json");stations=await res.json();stations=stations.map((s,i)=>({...s,uid:s.id??i+1,fields:s.fields||{}}));initFilters();bindEvents();applyFilters();document.getElementById("totalCount").textContent=stations.length;}
function initMap(){map=L.map("map",{zoomControl:true,preferCanvas:true}).setView([36.4,127.8],7);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap"}).addTo(map);markerLayer=L.layerGroup().addTo(map);routeLayer=L.layerGroup().addTo(map);}
function initFilters(){const rivers=[...new Set(stations.map(s=>s.river||"기타"))].sort();const groups=[...new Set(stations.map(s=>s.group||"미분류"))].sort();state.rivers=new Set(rivers);state.groups=new Set(groups);const rb=document.getElementById("riverFilters");rb.innerHTML="";rivers.forEach(r=>{const chip=document.createElement("button");chip.className="filter-chip active";chip.textContent=`${r} ${stations.filter(s=>s.river===r).length}`;chip.onclick=()=>{toggleSet(state.rivers,r);chip.classList.toggle("active",state.rivers.has(r));applyFilters();};rb.appendChild(chip);});const gb=document.getElementById("groupFilters");gb.innerHTML="";groups.forEach(g=>{const chip=document.createElement("button");chip.className="filter-chip active";chip.textContent=g;chip.onclick=()=>{toggleSet(state.groups,g);chip.classList.toggle("active",state.groups.has(g));applyFilters();};gb.appendChild(chip);});document.getElementById("groupCount").textContent=`${groups.length}개`;}
function bindEvents(){document.getElementById("searchInput").oninput=e=>{state.search=e.target.value.trim().toLowerCase();applyFilters();};document.getElementById("resetFilterBtn").onclick=()=>{state.search="";document.getElementById("searchInput").value="";state.rivers=new Set([...new Set(stations.map(s=>s.river||"기타"))]);state.groups=new Set([...new Set(stations.map(s=>s.group||"미분류"))]);document.querySelectorAll(".filter-chip").forEach(e=>e.classList.add("active"));applyFilters();};document.getElementById("fitBtn").onclick=fitVisibleMarkers;document.getElementById("closeDetailBtn").onclick=()=>document.getElementById("detailPanel").classList.add("hidden");document.getElementById("routeModeBtn").onclick=()=>{routeMode=!routeMode;document.getElementById("routeModeBtn").textContent=routeMode?"루트 설정 중":"점검 루트 설정";document.getElementById("routePanel").classList.toggle("hidden",!routeMode&&routeStations.length===0);};document.getElementById("clearRouteBtn").onclick=clearRoute;document.getElementById("downloadRouteBtn").onclick=downloadRoute;}
function toggleSet(set,v){set.has(v)?set.delete(v):set.add(v)}
function applyFilters(){filteredStations=stations.filter(s=>{const r=s.river||"기타",g=s.group||"미분류";if(!state.rivers.has(r)||!state.groups.has(g))return false;if(!state.search)return true;const hay=[s.name,s.river,s.group,s.lat,s.lng,...Object.keys(s.fields||{}),...Object.values(s.fields||{})].join(" ").toLowerCase();return hay.includes(state.search);});renderMarkers();renderStationList();document.getElementById("visibleCount").textContent=filteredStations.length;document.getElementById("currentTitle").textContent=state.search?`"${state.search}" 검색 결과`:"전체 관측소";document.getElementById("currentSubtitle").textContent=`${filteredStations.length}개 관측소 표시 중`;if(filteredStations.length)fitVisibleMarkers();}
function renderMarkers(){markerLayer.clearLayers();markers.clear();filteredStations.forEach(s=>{const m=L.circleMarker([s.lat,s.lng],{radius:8,color:"#fff",weight:2,fillColor:riverColors[s.river]||riverColors.기타,fillOpacity:.92});m.bindPopup(makePopupHtml(s));m.on("click",()=>{routeMode?addToRoute(s):showDetail(s)});m.addTo(markerLayer);markers.set(s.uid,m);});}
function renderStationList(){const list=document.getElementById("stationList");list.innerHTML="";if(!filteredStations.length){list.innerHTML='<div class="station-item"><div class="station-address">검색 결과가 없습니다.</div></div>';return;}filteredStations.forEach(s=>{const item=document.createElement("div");item.className="station-item";const address=getField(s,["주소","찾아가는곳","주소 (찾아가는 곳)"])||"주소 정보 없음";item.innerHTML=`<div class="station-name"><span>${escapeHtml(s.name)}</span><span class="river-badge">${escapeHtml(s.river||"기타")}</span></div><div class="station-address">${escapeHtml(address)}</div>`;item.onclick=()=>{const m=markers.get(s.uid);map.setView([s.lat,s.lng],16);if(m)m.openPopup();showDetail(s);};list.appendChild(item);});}
function makePopupHtml(s){const a=getField(s,["주소","찾아가는곳","주소 (찾아가는 곳)"])||"";return `<h3 class="popup-title">${escapeHtml(s.name)}</h3><div class="popup-meta">${escapeHtml(s.river||"")} · ${escapeHtml(s.group||"")}</div><div class="popup-meta">${escapeHtml(a)}</div><button class="popup-btn" onclick="window.__showStationDetail(${s.uid})">상세정보 보기</button>`;}
window.__showStationDetail=uid=>{const s=stations.find(x=>x.uid===uid);if(s)showDetail(s);};
function showDetail(s){const panel=document.getElementById("detailPanel"),content=document.getElementById("detailContent");const rows=Object.entries(s.fields||{}).map(([k,v])=>`<tr><th>${escapeHtml(k)}</th><td>${escapeHtml(v||"")}</td></tr>`).join("");content.innerHTML=`<h3 class="detail-title">${escapeHtml(s.name)}</h3><p class="detail-subtitle">${escapeHtml(s.river||"")} · ${escapeHtml(s.group||"")}<br>좌표: ${s.lat}, ${s.lng}</p><table class="detail-table"><tbody>${rows||"<tr><td>상세정보 없음</td></tr>"}</tbody></table>`;panel.classList.remove("hidden");}
function fitVisibleMarkers(){if(!filteredStations.length)return;const b=L.latLngBounds(filteredStations.map(s=>[s.lat,s.lng]));map.fitBounds(b,{padding:[70,70],maxZoom:13});}
function addToRoute(s){if(routeStations.some(x=>x.uid===s.uid))return;routeStations.push(s);renderRoute();}
function renderRoute(){routeLayer.clearLayers();if(routeLine){map.removeLayer(routeLine);routeLine=null;}document.getElementById("routePanel").classList.remove("hidden");const list=document.getElementById("routeList");list.classList.remove("empty");if(!routeStations.length){list.classList.add("empty");list.innerHTML="아직 선택된 관측소가 없습니다.";return;}list.innerHTML="";routeStations.forEach((s,i)=>{const a=getField(s,["주소","찾아가는곳","주소 (찾아가는 곳)"])||"";const icon=L.divIcon({className:"",html:`<div class="route-marker">${i+1}</div>`,iconSize:[30,30],iconAnchor:[15,15]});L.marker([s.lat,s.lng],{icon}).bindPopup(`${i+1}. ${escapeHtml(s.name)}`).addTo(routeLayer);const item=document.createElement("div");item.className="route-item";item.innerHTML=`<div class="route-name"><span class="route-order">${i+1}</span>${escapeHtml(s.name)}</div><div class="route-address">${escapeHtml(a)}</div>`;list.appendChild(item);});if(routeStations.length>=2)routeLine=L.polyline(routeStations.map(s=>[s.lat,s.lng]),{color:"#38bdf8",weight:4,opacity:.88,dashArray:"8, 8"}).addTo(map);}
function clearRoute(){routeStations=[];routeLayer.clearLayers();if(routeLine){map.removeLayer(routeLine);routeLine=null;}renderRoute();document.getElementById("routePanel").classList.add("hidden");}
function downloadRoute(){const route={route_name:"점검루트",created_at:new Date().toISOString(),stations:routeStations.map((s,i)=>({order:i+1,id:s.id,name:s.name,river:s.river,group:s.group,lat:s.lat,lng:s.lng,address:getField(s,["주소","찾아가는곳","주소 (찾아가는 곳)"])||"",fields:s.fields}))};const blob=new Blob([JSON.stringify(route,null,2)],{type:"application/json;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`booki_route_${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);}
function getField(s,keys){for(const k of keys){if(s.fields&&s.fields[k])return s.fields[k];}const p=/(서울|경기|강원|충북|충남|경북|경남|전북|전남|대구|부산|광주|대전|울산|세종|제주|인천)/;for(const [k,v] of Object.entries(s.fields||{})){if(p.test(v)&&k!=="이름")return v;}return "";}
function escapeHtml(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
